app/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
     content = TextAreaField('Tweet', validators=[DataRequired()])
     submit= SubmitField('Detect')
     

app/main/routes.py

from flask import Flask, render_template,  request,  Blueprint
from app.models import  Post, BlackandWhite

main= Blueprint('main',__name__)
@main.route("/")
@main.route("/home")
def home():
    page= request.args.get('page', 1, type=int)
    posts= Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    blackandwhite=BlackandWhite.query

    return render_template('home.html', posts=posts, blackandwhite=blackandwhite)


@main.route("/layout")
def layout():
    blackandwhite=BlackandWhite.query
    return render_template('layout.html', blackandwhite=blackandwhite)




@main.route("/about")
def about():
    blackandwhite=BlackandWhite.query
    return render_template('about.html', title="about", blackandwhite=blackandwhite)


app/posts/routes.py

import os
from flask import Flask, render_template, url_for, flash, redirect, request, abort, jsonify, Blueprint
import numpy as np
from app.posts.forms import PostForm
from app import  db
from app.models import  Post, Classification, Source, CredibleSources, BlackandWhite
from flask_login import current_user,  login_required
from werkzeug.utils import secure_filename
import joblib
from keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from fuzzywuzzy import fuzz
import torch.nn.functional as F
from fuzzywuzzy import process
import snscrape.modules.twitter as sntwitter
import requests
import json
import torch
from app.posts.utils import preprocess_input, check_internet_connection
import logging; logging.basicConfig(level = logging.DEBUG)
import pickle
from transformers import BertTokenizerFast,BertForSequenceClassification
import torch.nn as nn
import tweepy

posts=Blueprint('posts',__name__)

@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form=PostForm()
    blackandwhite=BlackandWhite.query
    #clf=joblib.load("akheeer.pkl")

    filepath = os.path.abspath('bertt.pkl')
    with open(filepath, 'rb') as f:
        model = pickle.load(f)

    if form.validate_on_submit():

        postContent= form.content.data
        


     




        #postContent=request.json['postContent']
        # input_ids, attention_mask= preprocess_input(postContent)
        # with torch.no_grad():
        #     clf.eval()
        #     outputs= clf(input_ids,attention_mask=attention_mask)
        #     logits=outputs[0]
        #     probabilities= torch.softmax(logits, dim=1)
        #     predicted_label=torch.argmax(probabilities, dim=1)
        #     predicted_label= predicted_label.item()
            
        # preds= jsonify({'label': predicted_label})


        input_text = [postContent]
        MAX_LENGTH = 15
        tokenizer = BertTokenizerFast.from_pretrained('bert-base-uncased')
        classifier = nn.Linear(model.config.hidden_size, 2)

        # Set the model to evaluation mode
        model.eval()

        inputs = tokenizer(input_text, padding=True, truncation=True, return_tensors='pt')

        # Pass the input through the model and the classification layer
        with torch.no_grad():
            outputs = model(**inputs)
            logits = classifier(outputs.pooler_output)

        # Get the predicted class
        predicted_class = torch.argmax(logits).item()

        # Map the predicted class index to the corresponding label
        prediction = 'Rumor' if predicted_class == 1 else 'Non-Rumor'

        # def predict_rumor(input_text):
        #     # Load tokenizer and model
        #     tokenizer = BertTokenizerFast.from_pretrained('bert-base-uncased', do_lower_case=True)

        #     # Tokenize input text
        #     input_ids = tokenizer.encode_plus(input_text, add_special_tokens=True, return_tensors='pt')['input_ids']
        #     attention_mask = tokenizer.encode_plus(input_text, add_special_tokens=True, return_tensors='pt')['attention_mask']

        #     # Make predictions
        #     with torch.no_grad():
        #         outputs = model(input_ids, attention_mask=attention_mask)
        #         logits = outputs[0]
        #         predictions = F.softmax(logits, dim=1).tolist()[0]

        #     return predictions

        # x=predict_rumor(input)
        # if x[0] > x[1]:
        #     prediction='Non Rumor'
        # else:
        #     prediction='Rumor'



        t=[]
        limit = 1


        des=[]
        src=[]
        publish=[]
        urll=[]

       
        if check_internet_connection():
            max_results = 10
            url = (f"https://newsapi.org/v2/everything?q={postContent}&sortBy=relevancy&pageSize={max_results}&apiKey=8bf358a5572d49e2a5713e84661e06d6")
            response = requests.get(url)
            response_json_string = json.dumps(response.json())
            response_dict = json.loads(response_json_string)
            response_dict
            for i in response_dict['articles']:

                    # print('description: '+i['description']+'\n')
                    # print('source: '+i['source']['name']+'\n')
                    # print('publishedAt: '+i['publishedAt']+'\n')
                    # print('url: '+i['url']+'\n')
                des.append(i['title'])
                src.append(i['source']['name'])
                publish.append(i['publishedAt'])
                urll.append(i['url'])
            res = len(des)
        else:
            print('')

            

        
        
        s1 = postContent
        s2 = des
        countR=0
        countN=0
        neutral=0
        percentR=0
        percentN=0
        percentNEU=0
        eval=''
        try:
            for i in range(res):
                if fuzz.WRatio(s1, s2[i])>80:
                    countN+=1
                elif fuzz.WRatio(s1, s2[i]) in range(45,80):
                    neutral+=1
                elif fuzz.WRatio(s1, s2[i])<45:
                    countR+=1
        except Exception as e:
            print('')
                            # print(countR)
        # print(countN)
        if countR > countN:
            eval='Rumor'
        elif countN > countR:
            eval='Not Rumor'
        else:
            eval='Neutral'
        
        userName=''
        isVerified=''
        followers=''

        
        
        # Your code to calculate percentR and percentN goes here
        try:
            percentR=int((countR/res)*100)
            percentN=int((countN/res)*100)
            percentNEU=int((neutral/res)*100)
        except Exception as e:
            print('')
    
        # Handle the exception here
        

        if check_internet_connection():
            access_token = "3251395693-EdEU7h9kbXD5suK68fws3P6HCLJHCl7xmCHJKAb" 
            access_token_secret = "EYKCF6YQbeIx4MXb827XY68pghZRgkT4J2HbHpqSyDoHo" 
            consumer_key = "BNwml9R6rQn48RMAZaWhFu8a4"
            consumer_secret = "9yY24HZQM6XFUf7575qBHuQYPAMRBNZZVcqa4He3iaYAlityhN"

            auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
            auth.set_access_token(access_token, access_token_secret)
            api = tweepy.API(auth)

            tweets = api.search_tweets(q=postContent, count=1, result_type='recent', tweet_mode='extended')
            if tweets:
                tweet = tweets[0]
                userName = tweet.user.screen_name
                isVerified = tweet.user.verified
                followers = tweet.user.followers_count
                t.append(userName)
                t.append(isVerified)
                t.append(followers)
            flash('Check your results!', 'success')
            
        else:
            flash("Check your connection",'danger')   
            
                
        if percentR> percentN :
            black= BlackandWhite(Black=userName)
            db.session.add(black)
        else:
            white=BlackandWhite(White=userName)
            db.session.add(white)

        result= Classification(classifierResult= prediction)
        source= Source( sourceUsername=userName, sourceVerified=isVerified, sourceFollowers=followers)
        credible=CredibleSources(percentr=percentR, percentn=percentN)
        post = Post( content= form.content.data, author_post= current_user, classif=result, sourc=source, cred=credible)

        db.session.add(result)
        db.session.add(source)
        db.session.add(credible)
        db.session.commit()
        db.session.add(post)
        try:
            if res==0:
                percentR=100
        except Exception as e:
            print('')
        return render_template('create_post.html', title='New Post', form= form, prediction=prediction, output2= postContent, one=userName,two=isVerified,three=followers,evalu=prediction,src= '' if not src else src,urll= '' if not urll else urll, blackandwhite=blackandwhite)
    else:
        prediction=''
        postContent=''
        return render_template('create_post.html', title='New Post', form= form, prediction=prediction, output2= postContent, one='',two='',three='', blackandwhite=blackandwhite) 

@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    blackandwhite=BlackandWhite.query
    return render_template('post.html', title=post.content, post=post, blackandwhite=blackandwhite)



@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post',
                           form=form, legend='Update Post')

@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))

app/users/routes.py

from flask import Flask, render_template, url_for, flash, redirect, request, Blueprint
from app.users.forms import RegistrationForm, LoginForm, UpdateAccountForm
from app import db, bcrypt
from app.models import User, Post, BlackandWhite
from flask_login import login_user, current_user, logout_user, login_required
from app.users.utils import save_picture









users= Blueprint('users', __name__)
@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form=RegistrationForm()
    blackandwhite=BlackandWhite.query

    if form.validate_on_submit():
        hashed_password=bcrypt.generate_password_hash(form.Password.data).decode('utf-8')
        user= User(username=form.username.data, email=form.email.data,password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f'Account created for {form.username.data} !', 'success')
        return redirect(url_for('users.login'))
    
    return render_template('regitser.html', title='Register', form=form, blackandwhite=blackandwhite)

@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form= LoginForm()
    blackandwhite=BlackandWhite.query
    if form.validate_on_submit():
       user= User.query.filter_by(email=form.email.data).first()
       if user and bcrypt.check_password_hash(user.password, form.Password.data):
            login_user(user, remember=form.remember.data)
            next_page=request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
       else:
            flash('Login Unsuccessfull, Please check Email and password', 'danger')

    return render_template('login.html', title='Login', form=form, blackandwhite=blackandwhite)

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route("/account", methods=['GET','POST'])
@login_required
def account():
    form = UpdateAccountForm()
    blackandwhite=BlackandWhite.query

    if form.validate_on_submit():
        if form.picture.data:
           picture_file = save_picture(form.picture.data)
           current_user.image_file = picture_file
        current_user.username= form.username.data
        current_user.email=form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method== 'GET':
        form.username.data= current_user.username
        form.email.data= current_user.email
    

    image_file= url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form= form, blackandwhite=blackandwhite)

@users.route("/user/<string:username>")
def user_posts(username):
    page= request.args.get('page', 1, type=int)
    user= User.query.filter_by(username=username).first_or_404()
    posts= Post.query.filter_by(author_post=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    blackandwhite=BlackandWhite.query
    return render_template('user_posts.html', posts=posts, user=user, blackandwhite=blackandwhite)

app/templates/about.html
{% extends "layout.html" %}
{% block content %}
<main role="main">
    <div class="container my-5">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <h1 class="text-center mb-4">About Us</h1>
                <p class="lead">We are a team of experts dedicated to detecting and debunking rumors and misinformation
                    online.</p>
                <p class="lead">Our mission is to provide accurate information to the public and combat the spread of
                    Rumors.</p>
                <p class="lead">If you have any questions or concerns, please feel free to contact us using the form on
                    our <a href="contact.html">Contact Us</a> page.</p>
            </div>
        </div>
    </div>
</main>

<footer class="py-3 bg-dark">
    <div class="container">
        <p class="text-white text-center">&copy; 2023 Rumor Detection Website</p>
    </div>
</footer>
</body>

</html>
{% endblock content %}

app/templates/account.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}" alt="">
        <div class="media-body">
            <h2 class="account-heading">{{ current_user.username }}</h2>
            <p class="text-secondary">{{ current_user.email }}</p>
        </div>
    </div>
    <div class=" content-section">
        <form action="" method="POST" enctype="multipart/form-data">
            {{ form.csrf_token }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Info</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}

                    {{ form.username(class="form-control is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.username.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.username(class="form-control") }}

                    {% endif %}


                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}

                    {{ form.email(class="form-control is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.email(class="form-control") }}

                    {% endif %}

                </div>
                <div class="form-group">
                    {{ form.picture.label() }}
                    {{ form.picture (class="form-control-file")}}
                    {% if form.picture.errors %}
                    {% for error in form.picture.errors %}
                    <span class="text-danger">{{ error }}</span><br>
                    {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
</div>
{% endblock content %}

app/templates/home.html
{% extends "layout.html" %}
{% block content %}
    {% for post in posts.items %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author_post.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="link-dark mb-2"  href="{{ url_for('users.user_posts', username=post.author_post.username) }}">{{ post.author_post.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2 class="font-weight-italic">{{ post.content }}</h2>
            <h4 class="text-danger">Rumor: {{ post.cred.percentr }}%</h4>
            <h4 class="text-success">Non-Rumor: {{ post.cred.percentn }}%</h4>

            <a href="{{ url_for('posts.post', post_id=post.id) }}">
              <button class="btn btn-primary mb-2" style="margin-left: 160px; margin-top: 10px;background-color:#5f788a;border-color:#5f788a;">View Classification Report</button>
            </a>
          </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-dark mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-dark mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
    <title>Rumors Detector - {{ title }}</title>
    {% else %}
    <title>Rumors Detector</title>
    {% endif %}
</head>

<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <div class="container">
                <a class="navbar-brand mr-4" href="{{ url_for('main.home') }}">Rumors Detector</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                    aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <div class="navbar-nav mr-auto">
                        <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
                        <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
                    </div>
                    <!-- Navbar Right Side -->
                    <div class="navbar-nav">
                        {% if current_user.is_authenticated %}
                        <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">Detect</a>

                        <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>

                        <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>

                        {% else %}
                        <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <main role="main" class="container">
        <div class="row">
            <div class="col-md-8">
                {% with messages= get_flashed_messages(with_categories=true) %}
                {% if messages %}
                {% for category, message in messages %}
                <div class="alert  alert-{{ category }}">
                    {{ message }}
                </div>
                {% endfor %}
                {% endif %}
                {% endwith %}
                {% block content %}{% endblock %}
            </div>
            <div class="col-md-4">
                <div class="content-section">
                    <h3>Black & White List (Twitter usernames)</h3>
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th scope="col"></th>
                                <th scope="col">Black</th>
                                <th scope="col">White</th>
                            </tr>
                        </thead>
                        <tbody>

                            <tr>
                                <th scope="row"></th>
                                <td>
                                    {% for bw in blackandwhite %}
                                    {% if bw.Black %}


                                    @{{ bw.Black }}
                                    <hr>
                                    {% endif %}

                                    {% endfor %}

                                </td>

                                <td>
                                    {% for bw in blackandwhite %}
                                    {% if bw.White %}


                                    @{{ bw.White }}
                                    <hr>
                                    {% endif %}


                                    {% endfor %}

                                </td>
                            </tr>

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </main>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

</body>

</html>

app/templates/login.html
{% extends "layout.html" %}
{% block content %}
<div class=" content-section">
    <form action="" method="POST">
        {{ form.csrf_token }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Login</legend>
            
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}

                {{ form.email(class="form-control is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email(class="form-control") }}

                {% endif %}

            </div>
            <div class="form-group">
                {{ form.Password.label(class="form-control-label") }}
                {% if form.Password.errors %}

                {{ form.Password(class="form-control is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.Password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.Password(class="form-control") }}

                {% endif %}

            </div>
           <div class="form-check">
                {{ form.remember(class="form-check-input") }}
                {{ form.remember.label(class="form-check-label") }}
           </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-dark") }}
        </div>
        <small class="text-muted ml-2">
            <a href="#" class="link-dark">Forgot Password?</a>
        </small>
    </form>
</div>
<div class="border-top pt-3">
    <small class="text-muted">
        Need An Account? <a href="{{ url_for('users.register') }}" class="link-dark ml2-2">Sign Up Now!</a>
    </small>
</div>
{% endblock %}

app/templates/post.html
{% extends "layout.html" %}
{% block content %}
  <article class="media content-section">
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author_post.image_file) }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="link-dark" href="{{ url_for('users.user_posts', username=post.author_post.username) }}">{{ post.author_post.username }}</a>
        <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
       
      </div>
      <h2 class="article-content" style="margin-left:20px; margin-top:10px">  {{ post.content }}</p>
  <h4 style="text-align: center;">Twitter Source Username: {{ post.sourc.sourceUsername }}</h4>
  <hr>
  <h4 style="text-align: center;">Twitter Source Verification: {{ post.sourc.sourceVerified }}</h4>
  <hr>
  <h4 style="text-align: center;">Twitter Source Followers: {{ post.sourc.sourceFollowers}}</h4>
  <hr>
  <h4 style="text-align: center;" class="text-danger">Rumor: {{ post.cred.percentr }}%</h4>
  <hr>
  <h4 style="text-align: center;" class="text-success"> Non-Rumor: {{ post.cred.percentn }}%</h4>
  <hr>
    </div>
  </article>
  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
      
    </div>
    
  </div>
  




  

{% endblock content %}

app/templates/user_posts.html
{% extends "layout.html" %}
{% block content %}
<div class="jumbotron" style="height:100px; width: 700px">
<h1 class="h1 mb-3" style="margin-top:-20px">Detections By {{ user.username }} ({{ posts.total }})</h1>
</div>
{% for post in posts.items %}
<article class="media content-section">
  <img class="rounded-circle article-img"
    src="{{ url_for('static', filename='profile_pics/' + post.author_post.image_file) }}">
  <div class="media-body">
    <div class="article-metadata">
      <a class="link-dark mr-2" href="{{ url_for('users.user_posts', username=post.author_post.username) }}">{{
        post.author_post.username }}</a>
      <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
    </div>
    <h2 class="article-content">{{ post.content }}</h2>
    <h4 class="text-danger">Rumor: {{ post.cred.percentr }}%</h4>
    <h4 class="text-success">Non-Rumor: {{ post.cred.percentn }}%</h4>
    <a href="{{ url_for('posts.post', post_id=post.id) }}">
      <button class="btn btn-primary mb-2"" style="margin-left: 160px; margin-top: 10px;background-color:#5f788a; border-color:#5f788a;">view classification report</button>
    </a>
  </div>
</article>
{% endfor %}
{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
{% if page_num %}
{% if posts.page == page_num %}
<a class="btn btn-dark mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num
  }}</a>
{% else %}
<a class="btn btn-outline-dark mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{
  page_num }}</a>
{% endif %}
{% else %}
...
{% endif %}
{% endfor %}
{% endblock content %}